include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]

linter:
  rules:
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true
    eol_at_end_of_file: true
    always_specify_types: true
    annotate_overrides: true
    prefer_relative_imports: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
